server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: User-service
          uri: http://localhost:9010
          predicates:
            - Path=/auth/**

        - id: EventManagementService
          uri: http://localhost:9020
          predicates:
            - Path=/events/**




feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secretKey: vfkgblrigfreifiehgitughibfdkvbhvbfdvdfivbfdkjvbfvnjdfknvbuiehvebfkvbdfibvfgvregvhrguvfdvfbvfnvjdgfvhuibvkfgbf
